# Generated by Django 5.1.4 on 2025-01-13 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_code", models.CharField(max_length=25, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("SS", "Senior Staff"),
                            ("CoS", "Contract Staff"),
                            ("CaS", "Casual Staff"),
                        ],
                        max_length=3,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("designation", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("grade_level", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                ("no_of_days", models.IntegerField()),
                ("actual_attendance", models.IntegerField()),
                (
                    "rent_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "meal_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "utility_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "overtime",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "arrears",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "staff_loan_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rent_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "medical_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pension_contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shortage_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "development_levy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "personal_income_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("salary_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary",
                "verbose_name_plural": "Salaries",
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.salary",
                    ),
                ),
            ],
        ),
    ]
